# Generated by Django 4.2.3 on 2023-08-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
