# Generated by Django 4.2.3 on 2023-08-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cartitem_price_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
